<?php

namespace ufsw\DataBaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadisticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadisticaRepository extends EntityRepository
{
}
