<?php

namespace ufsw\DataBaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidoRepository extends EntityRepository
{
}
